#%RAML 1.0 DataType
    properties:
      Latitude: 
        type: number
        required: false
        example: 34.134439
      Longitude: 
        type: number
        required: false
        example: -84.497129