#%RAML 1.0 Library
usage: flight information

types: 
  flight:
    properties:
      airlineName: string
      code: string
      departureDate: datetime-only
      origin: string
      destination: string
      planeType: string
      price: number
      emptySeats: integer