#%RAML 1.0 DataType
properties: 
  label: string
  details: string
  SiteSystemID: !include systemID.raml
  LocationID: integer
  StatusReferenceID: !include systemID.raml
  Address: !include address.raml