#%RAML 1.0 Trait
queryParameters:
  firstPage:
    type: string
    required: false
  previousPage:
    type: string
    required: false
  nextPage:
    type: string
    required: false
  lastPage:
    type: string
    required: false